# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: HackerNews
  
securityDefinitions:
  apiKey:
    type: apiKey
    description: Té la clau de usuari generada. Es pot extreure desde la interficie grafica de la aplicació
    name: api_key
    in: header

# Describe your paths here
paths:
  /api/posts/ask:
    get:
      security:
        - apiKey: []
      description: |
        Retorna una llista de posts de tipus "Ask" ordenades cronològicament per data de publicació
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Ask'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /api/posts/url:
    get:
      security:
        - apiKey: []
      description: |
        Retorna una llista de posts de tipus "Url" ordenades cronològicament per data de publicació
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Url'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /api/posts/:id:
    get:
      security:
        - apiKey: []
      description: |
        Retorna la informació d'un post
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Post'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /api/comments/:id:
    get:
      security:
        - apiKey: []
      description: |
        Retorna la informació d'un comentari
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Comment'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Post:
    type: object
    properties:
      title:
        type: string
      contr_subtype:
        type: string
      content:
        type: string
      user_id:
        type: integer
      url:
        type: string
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  Ask:
    type: object
    properties:
      title:
        type: string
      content:
        type: string
      user_id:
        type: integer
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  Url:
    type: object
    properties:
      title:
        type: string
      user_id:
        type: integer
      url:
        type: string
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  Comment:
    type: object
    properties:
      content:
        type: string
      user_id:
        type: integer
      parent_id:
        type: integer
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string