# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: HackerNews

securityDefinitions:
  apiKey:
    type: apiKey
    description: Té la clau de usuari generada. Es pot extreure desde la interficie grafica de la aplicació
    name: Authorization
    in: header

# Describe your paths here
paths:
  /api/votes:
    post:
      security:
        - apiKey: []
      description: |
        Creates new vote.
      parameters:
        -
          name: contribution_id
          in: formData
          description: Contribution identifier
          required: true
          type: number
      responses:
        200:
          description: Succesfully created
          schema:
            title: vote
            type: object
            properties:
              contribution_id:
                type: integer
              user_id:
                type: integer


                  
  /api/posts:
    post:
      security:
          - apiKey: []
      description: |
        Create a new post, question or link
      parameters:
        - name: title
          in: body
          description: title of the submission
          required: true
          type: text
        - name: url
          in: body
          description: Url of the link (empty if question)
          required: false
          type: url
        - name: text
          in: body
          description: Text of the question (empty if link)
          required: false (ccant be false both)
          type: text
      
      responses:
        200:
          description: Succesfully created
          schema:
            title: posts
            type: object
            properties:
              contribution_id:
                type: integer
              user_id:
                type: integer
          
          
          
  /api/comments:
    post:
      security:
          - apiKey: []
      description: |
        Create a new comment of a post
      parameters:
        - name: comment
          in: body
          description: body of the comment
          required: true
          type: text
        -
          name: contribution_id
          in: formData
          description: Contribution identifier
          required: true
          type: number
      
          responses:
        200:
          description: Succesfully created
          schema:
            title: comments
            type: object
            properties:
              contribution_id:
                type: integer
              user_id:
                type: integer
                
                
          
          
  /api/replies:
    post:
      security:
          - apiKey: []
      description: |
        Create a new reply of a comment
      parameters:
        - name: contribution_id
          in: formData
          description: Contribution identifier
          required: true
          type: number
        - name: reply
          in: body
          description: body of the comment
          required: true
          type: text
      
          responses:
        200:
          description: Succesfully created
          schema:
            title: replies
            type: object
            properties:
              contribution_id:
                type: integer
              user_id:
                type: integer       