# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: HackerNews
  
securityDefinitions:
  Token:
    type: apiKey
    description: Té la clau de usuari generada. Es pot extreure desde la interficie grafica de la aplicació
    name: Authorization
    in: header
produces:
  - application/json
host: localhost:3000
# Describe your paths here
paths:
  /api/replies/{id}:
      get:
        description:
          Retorna la informació d'una replica.
        parameters:
          -
            name: id
            in: path
            description: Identificador de la replica
            required: true
            type: integer
            format: int64
        responses:
          200:
            description: La replica ja existeix
            schema:
              $ref: '#/definitions/Reply'
          404:
            description: Not found
            schema:
              type: object
              properties:
                error:
                  type: string

  /api/votes:
      post:
        security:
          - Token: []
        description: |
          Crea un nou vot
        parameters:
          -
            name: contribution_id
            in: formData
            description: identificador de la contribució a votar
            required: true
            type: number
        responses:
          200:
            description: Succesfully created
            schema:
              $ref: '#/definitions/Vote'
          400:
            description: L'usuari ja ha votat
            schema:
              type: object
              properties:
                user_id:
                  type: array
                  items:
                    type: string
          403:
            description: No autoritzat
            schema:
              type: object
              properties:
                error:
                  type: string


  /api/posts/ask:
      get:
        description:
          Retorna una llista de posts de tipus "Ask" ordenades cronològicament per data de publicació
        responses:
          200:
            description: Successful response
            schema:
              type: array
              items:
                $ref: '#/definitions/Post'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /api/posts/url:
      get:
        description:
          Retorna una llista de posts de tipus "Url" ordenades cronològicament per data de publicació
        responses:
          200:
            description: Successful response
            schema:
              type: array
              items:
                $ref: '#/definitions/Post'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /api/posts/{id}:
      get:
        description:
          Retorna la informació d'un post
        parameters:
          - name: id
            in: path
            description: ID del post (ask o url)
            required: true
            type: integer
            format: int64
        responses:
          200:
            description: Successful response
            schema:
              $ref: '#/definitions/Post'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'

  /api/comments/{id}:
      get:
        description:
          Retorna la informació d'un comentari
        parameters:
          - name: id
            in: path
            description: ID del comentari
            required: true
            type: integer
        responses:
          200:
            description: Successful response
            schema:
              $ref: '#/definitions/Comment'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'

  /api/posts:
      post:
        security:
            - Token: []
        description: |
          Create a new post, question or link
        parameters:
          -
            name: title
            in: formData
            description: title of the submission
            required: true
            type: string
          -
            name: url
            in: formData
            description: Url of the link (empty if question)
            required: false
            type: string
          -
            name: text
            in: formData
            description: Text of the question (empty if link)
            required: false
            type: string

        responses:
          200:
            description: Succesfully created
            schema:
              $ref: '#/definitions/Post'


  /api/comments:
      post:
        security:
            - Token: []
        description: |
          Create a new comment of a post
        parameters:
          - name: comment
            in: formData
            description: body of the comment
            required: true
            type: string
          -
            name: parent_id
            in: formData
            description: Identificador de la contribució sobre la que comentem
            required: true
            type: number

        responses:
          200:
            description: Succesfully created
            schema:
              $ref: '#/definitions/Comment'

  /api/replies:
      post:
        security:
            - Token: []
        description:
          Create a new reply of a comment
        parameters:
          -
            name: parent_id
            in: formData
            description: Identificador del comentari sobre el que fem una replica
            required: true
            type: number

          - name: reply
            in: formData
            description: Contigut de la replica
            required: true
            type: string
        responses:
          200:
            description: Succesfully created
            schema:
              $ref: '#/definitions/Reply'

/api/users/{id}:
    get:
      description: |
        Gets specific user.
      parameters:
        -
          name: id
          in: path
          description: User identifier
          required: true
          type: number
      responses:
        200:
          description: Succesfully get
          schema:
             $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    put:
      security:
        - Token: []
      description:
        Edit user
      parameters:
        -
          name: id
          in: path
          description: User identifier
          required: true
          type: number
        -
          name: name
          in: formData
          description: User name
          required: false
          type: string
      responses:
        200:
          description: Succesfully update
          schema:
            $ref: '#/definitions/User'
        401:
          description: Unathorized user
          schema:
            type: object
            properties:
              error:
                type: string

  /api/users/{id}/threads:
    get:
      security:
        - Token: []
      description: |
        Gets specific user.
      parameters:
        -
          name: id
          in: path
          description: User identifier
          required: true
          type: number
      responses:
        200:
          description: Succesfully get
          schema:
             $ref: '#/definitions/Contribution'


definitions:
  Post:
    type: object
    properties:
      title:
        type: string
      contr_subtype:
        type: string
      content:
        type: string
      user_id:
        type: integer
      url:
        type: string
      parent_id:
        type: integer
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string

  Comment:
    type: object
    properties:
      title:
        type: string
      contr_subtype:
        type: string
      content:
        type: string
      user_id:
        type: integer
      url:
        type: string
      parent_id:
        type: integer
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string

  Reply:
    type: object
    properties:
      title:
        type: string
      contr_subtype:
        type: string
      content:
        type: string
      user_id:
        type: integer
      url:
        type: string
      parent_id:
        type: integer
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
  Vote:
      type: object
      properties:
        contribution_id:
          type: integer
          format: int32
        id:
          type: integer
          format: int32
        user_id:
          type: integer
          format: int32
        created_at:
          type: string
        updated_at:
          type: string
  User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string

