# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: HackerNews
  
securityDefinitions:
  Token:
    type: apiKey
    description: Té la clau de usuari generada. Es pot extreure desde la interficie grafica de la aplicació
    name: Authorization
    in: header
produces:
  - application/json
host: hackersnews.herokuapp.com
# Describe your paths here
paths:
  /api/replies/{id}:
      get:
        description:
          Obtains replies by id
        parameters:
          -
            name: id
            in: path
            description: ID del reply
            required: true
            type: integer
            format: int64
        responses:
          200:
            description: Existing reply
            schema:
              $ref: '#/definitions/Contribution'
          404:
            description: Not found
            schema:
              type: object
              properties:
                error:
                  type: string

  /api/votes:
      post:
        security:
          - Token: []
        description: |
          Creates new vote.
        parameters:
          -
            name: contribution_id
            in: formData
            description: Contribution identifier
            required: true
            type: number
        responses:
          200:
            description: Succesfully created
            schema:
              $ref: '#/definitions/Vote'
          400:
            description: User already voted
            schema:
              type: object
              properties:
                user_id:
                  type: array
                  items:
                    type: string
          403:
            description: Non authorized
            schema:
              type: string


  /api/posts/ask:
    get:
      description: |
        Retorna una llista de posts de tipus "Ask" ordenades cronològicament per data de publicació
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Contribution'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /api/posts/url:
    get:
      description: |
        Retorna una llista de posts de tipus "Url" ordenades cronològicament per data de publicació
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Contribution'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /api/posts/{id}:
    get:
      description: |
        Retorna la informació d'un post
      parameters:
        - name: id
          in: path
          description: ID del post (ask o url)
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Contribution'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /api/comments/{id}:
    get:
      description: |
        Retorna la informació d'un comentari
      parameters:
        - name: id
          in: path
          description: ID del comentari
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Contribution'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /api/users/{id}:
    get:
      security:
        - apiKey: []
      description: |
        Gets specific user.
      parameters:
        -
          name: id
          in: path
          description: User identifier
          required: true
          type: number
      responses:
        200:
          description: Succesfully get
          schema:
             $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    put:
      security:
        - apiKey: []
      description:
        Edit user
      parameters:
        -
          name: id
          in: path
          description: User identifier
          required: true
          type: number
      responses:
        200:
          description: Succesfully update
          schema:
            $ref: '#/definitions/User'

  /api/users/{id}/threads:
    get:
      security:
        - apiKey: []
      description: |
        Gets specific user.
      parameters:
        -
          name: id
          in: path
          description: User identifier
          required: true
          type: number
      responses:
        200:
          description: Succesfully get
          schema:
             $ref: '#/definitions/Contribution'

definitions:
  Contribution:
    type: object
    properties:
      title:
        type: string
      contr_subtype:
        type: string
      content:
        type: string
      user_id:
        type: integer
      url:
        type: string
      parent_id:
        type: integer
      upvote:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
  Vote:
      type: object
      properties:
        contribution_id:
          type: integer
          format: int32
        id:
          type: integer
          format: int32
        user_id:
          type: integer
          format: int32
        created_at:
          type: string
        updated_at:
          type: string
      User:
        type: object
        properties:
          username:
            type: string
          email:
            type: string

